[build]
  # Branch to deploy
  base = "main"  # ou la branche que vous utilisez pour le développement principal

  # Build command
  command = "npm run build"  # ou toute autre commande spécifiée dans vos scripts package.json pour construire votre application

  # Directory with build output
  publish = "public"  # le répertoire où les fichiers statiques sont générés après la construction (par exemple, public, dist, etc.)

  # Optional: Functions directory if using Netlify functions (Lambda functions)
  # functions = "functions"  # le répertoire contenant les fonctions Netlify (facultatif)
